CREATE TABLE `documentTemplates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`type` enum('quote','invoice') NOT NULL,
	`name` varchar(255) NOT NULL,
	`logoUrl` text,
	`primaryColor` varchar(7) DEFAULT '#E67E50',
	`secondaryColor` varchar(7) DEFAULT '#1E293B',
	`companyName` varchar(255),
	`companyAddress` text,
	`companyPhone` varchar(50),
	`companyEmail` varchar(255),
	`companySiret` varchar(50),
	`companyTva` varchar(50),
	`legalMentions` text,
	`termsAndConditions` text,
	`footerText` text,
	`isDefault` boolean DEFAULT false,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `documentTemplates_id` PRIMARY KEY(`id`)
);
